package com.paytm.pgplus.constants;

/**
 * Created by Naman on 12/06/17.
 */
public enum EApiResponseKeys {

    CREATE_ORDER, CREATE_TOPUP, CREATE_ORDER_AND_PAY, CONSULT_PAYVIEW, ADD_AND_PAY_CONSULT_PAYVIEW, QUERY_BY_ACQUIREMENT_ID, PAY_RESULT_QUERY, WALLET_CONSULT, FETCH_USER_DETAILS, BULK_CHARGE_FEE_CONSULT;

}
