package com.paytm.pgplus.biz.taskengine.common;

/**
 * Created by charu on 08/06/18.
 */
public enum TaskName {
    CREATE_ORDER("CREATE_ORDER"), FETCH_SAVED_CARD("FETCH_SAVED_CARD"), AUTHENTICATE_USER("AUTHENTICATE_USER"), LITEPAYVIEW_CONSULT(
            "LITEPAYVIEW_CONSULT"), PAYMENTS_BANK_BALANCE("PAYMENTS_BANK_BALANCE"), VALIDATE_REQUEST_TASK(
            "VALIDATE_REQUEST_TASK"), FETCH_VPA("FETCH_VPA"), PAYMODE_DECISION_MAKER_TASK("PAYMODE_DECISION_MAKER_TASK"), CHANNEL_ACCOUNT_QUERY_TASK(
            "CHANNEL_ACCOUNT_QUERY_TASK"), CONSULT_FEE_TASK("CONSULT_FEE_TASK"), FRESH_SUBSCRIPTION_CONTRACT_TASK(
            "FRESH_SUBSCRIPTION_CONTRACT_TASK"), FETCH_SAVED_CARD_NO_FILTER("FETCH_SAVED_CARD_NO_FILTER"), FILTER_SAVED_CARD(
            "FILTER_SAVED_CARD"), FETCH_POSTPAID("FETCH_POSTPAID_BALANCE"), FETCH_WALLET("FETCH_WALLET_BALANCE"), CREATE_TOPUP(
            "CREATE_TOPUP"), AUTH_USER_TYPE_ATTRIBUTE("AUTH_USER_TYPE_ATTRIBUTE"), SUBSCRIPTION_SPECIFIC_PAYOPTION_SAVEDCARD_FILTER(
            "SUBSCRIPTION_SPECIFIC_PAYOPTION_SAVEDCARD_FILTER"), VALIDATE_USER_FOR_ADVANCE_DEPOSIT(
            "VALIDATE_USER_FOR_ADVANCE_DEPOSIT"), CREATE_DYNAMIC_QR("CREATE_DYNAMIC_QR"), RISK_POLICY_CONSULT(
            "RISK_POLICY_CONSULT"), MERCHANT_EMI_DETAILS("MERCHANT_EMI_DETAILS"), FETCH_MGV("FETCH_MGV_BALANCE"), MERCHANT_TOTAL_LIMIT_TASK(
            "MERCHANT_TOTAL_LIMIT_TASK"), MERCHANT_PAYMODES_LIMIT_TASK("MERCHANT_PAYMODES_LIMIT_TASK"), MERCHANT_ACCUMULATED_LIMIT_TASK(
            "MERCHANT_ACCUMULATED_LIMIT_TASK"), NATIVE_FETCH_VPA("NATIVE_FETCH_VPA"), FETCH_EMI_SUBVENTION_BULK_SAVEDCARD_TASK(
            "FETCH_EMI_SUBVENTION_BULK_SAVEDCARD_TASK"), FETCH_EMI_SUBVENTION_BULK_CARD_INDEX_TASK(
            "FETCH_EMI_SUBVENTION_BULK_CARD_INDEX_TASK"), FETCH_EMI_SUBVENTED_BANKS("FETCH_EMI_SUBVENTED_BANKS"), FETCH_UPI_PROFILE(
            "FETCH_UPI_PROFILE"), FETCH_CHANNEL_DETAILS("FETCH_CHANNEL_DETAILS"), REAL_TIME_SAVEDCARD_RECON(
            "REAL_TIME_SAVEDCARD_RECON"), FILTER_PLATFORM_SAVED_ASSETS_FOR_SUBSCRIPTION_TASK(
            "FILTER_PLATFORM_SAVED_ASSETS_FOR_SUBSCRIPTION_TASK"), FILTER_PLATFROM_SAVED_ASSETS(
            "FILTER_PLATFROM_SAVED_ASSETS"), FETCH_MANDATE_BANK_AND_PSP("FETCH_MANDATE_BANK_AND_PSP"), SEND_SMS_APP_INVOKE(
            "SEND_SMS_APP_INVOKE"), FETCH_SHORTEN_URL("FETCH_SHORTEN_URL"), SEND_NOTIFICATION_APP_INVOKE(
            "SEND_NOTIFICATION_APP_INVOKE"), FETCH_PPBL_BALANCE("FETCH_PPBL_BALANCE"), GET_TOKENIZED_CARDS(
            "GET_TOKENIZED_CARDS_IN_FPO"), FILTER_TOKENIZED_AND_PLATFORM_CARDS("FILTER_TOKENIZED_AND_PLATFORM_CARDS"), ADD_N_PAY_FILTER_TOKENIZED_AND_PLATFORM_CARDS(
            "ADDNPAY_FILTER_TOKENIZED_AND_PLATFORM_CARDS"), FETCH_USER_PREFERENCES_TASK("FETCH_USER_PREFERENCES_TASK"), GET_PLATFORM_AND_TOKENIZED_CARDS(
            "GET_PLATFORM_AND_TOKENIZED_CARDS"), FILTER_AOA_TOKENIZED_AND_PLATFORM_CARDS(
            "FILTER_AOA_TOKENIZED_AND_PLATFORM_CARDS"), FETCH_LIMIT_CONSUMPTION_TASK("FETCH_LIMIT_CONSUMPTION_TASK"), ADDNPAY_LITEPAYVIEW_CONSULT(
            "ADDNPAY_LITEPAYVIEW_CONSULT"), FETCH_PAYTM_VPA("FETCH_PAYTM_VPA"), ADDNPAY_GET_TOKENIZED_CARDS(
            "GET_TOKENIZED_CARDS_IN_FPO_FOR_ADDNPAY"), FETCH_SAVED_CARD_LIMIT_TASK("FETCH_SAVED_CARD_LIMIT_TASK"), FETCH_WORKFLOW_ID_WALLET_2FA_WEB(
            "FETCH_WORKFLOW_ID_WALLET_2FA_WEB");

    private String value;

    public String getValue() {
        return value;
    }

    TaskName(String taskName) {
        this.value = taskName;
    }

    public String getCounterName() {
        return "COUNTER_" + value;
    }

    public String getTimerName() {
        return "TIMER_" + value;
    }
}
